#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroxylicious-proxy
  labels:
    app: kroxylicious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kroxylicious
  template:
    metadata:
      labels:
        app: kroxylicious
    spec:
      containers:
      - name: kroxylicious
        image: quay.io/kroxylicious/kroxylicious:0.14.0
        imagePullPolicy: Always
        args: ["--config", "/opt/kroxylicious/config/config.yaml"]
        ports:
        - containerPort: 9190
          name: metrics
        - containerPort: 9292
        - containerPort: 9293
        - containerPort: 9294
        - containerPort: 9295
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kroxylicious/config/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: kroxylicious-config
