#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
data:
  config.yaml: |
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      demo:
        targetCluster:
          bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        listeners:
          - name: mylistener
            portIdentifiesNode:
              bootstrapAddress: localhost:9292
              advertisedBrokerAddressPattern: kroxylicious-service
              nodeIdRanges:
                - name: pool-1
                  start: 0
                  end: 4
                - name: pool-2
                  start: 10
                  end: 14
        logNetwork: false
        logFrames: false
