#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kroxylicious

resources:
- kroxylicious-namespace.yaml
- kroxylicious-config.yaml
- kroxylicious-deployment.yaml
- kroxylicious-service.yaml

