#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
data:
  config.yaml: |
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      - name: my-cluster-proxy
        # the virtual cluster is kafka proxy that sits between kafka clients and the real kafka cluster.  clients
        # connect to the virtual cluster rather than real cluster.
        gateways:
          - name: mygateway
            # this is the networking scheme used to present the virtual cluster on the network
            portIdentifiesNode:
              bootstrapAddress: minikube:30192
        targetCluster:
          # declares the kafka cluster that is being proxied
          bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        logFrames: false
    filterDefinitions:
    - name: encrypt
      type: RecordEncryption
      config:
        kms: VaultKmsService
        kmsConfig:
          vaultTransitEngineUrl: http://vault.vault.svc.cluster.local:8200/v1/transit
          vaultToken:
            password: myroottoken
        selector: TemplateKekSelector
        selectorConfig:
          template: "$(topicName)"
    defaultFilters:
      - encrypt
