#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  demo:
    targetCluster:
      bootstrapServers: localhost:9092
    listeners:
    - name: mylistener
      portIdentifiesNode:
        bootstrapAddress: localhost:9192
    logNetwork: false
    logFrames: false
filterDefinitions:
#- name: toUpper
#  type: ProduceRequestTransformation
#  config:
#    transformation: UpperCasing
#    transformationConfig:
#      charset: UTF-8
#defaultFilters:
#  - toUpper