#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: localhost:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBroker
      config:
        bootstrapAddress: localhost:9192
    logNetwork: false
    logFrames: false
filters:
  - type: ApiVersions
  - type: SampleProduceRequest
    config:
      findValue: foo
      replacementValue: bar
  - type: SampleFetchResponse
    config:
      findValue: bar
      replacementValue: baz
