#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

apiVersion: v2
name: kroxylicious-benchmark
description: OpenMessaging Benchmark for Kroxylicious
version: 0.1.0
appVersion: "0.18.0"
icon: https://raw.githubusercontent.com/kroxylicious/kroxylicious.github.io/main/assets/img/kroxylicious-logo.svg
