#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements. See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
name: "Run Kroxylicious Proxy Integration Tests"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  discover_integration_test_chunks:
    runs-on: ubuntu-latest
    outputs:
      test_chunks: ${{ steps.discover.outputs.test_chunks }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: 'Discover ITs'
        working-directory: kroxylicious-integration-tests
        id: discover
        run: |
          TESTS_PER_CHUNK=5
          TEST_CHUNKS="[$(find . -type f -name "*IT.java" -exec basename {} .java \; | xargs -L ${TESTS_PER_CHUNK} | tr ' ' , | sed 's/.*/"&"/' | sed -z 's/\n/,/g;s/,$/\n/')]"
          echo "test_chunks=$TEST_CHUNKS" >> $GITHUB_OUTPUT
  run_integration_tests:
    needs: discover_integration_test_chunks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests: ${{ fromJson(needs.discover_integration_test_chunks.outputs.test_chunks) }}
    steps:
      - name: Log tests to run
        run: echo "Running tests on classes '${{ matrix.tests }}'"
      - name: 'Check out repository'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: ./.github/actions/common/setup-java
      - name: 'Cache Maven packages'
        uses: ./.github/actions/common/cache-maven-packages
      - name: 'Build Kroxylicious proxy integration tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B install -DskipTests -Dmaven.javadoc.skip=true -DskipDocs=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Djapicmp.skip=true -pl :kroxylicious-bom,:kroxylicious-integration-tests,:kroxylicious-filter-archetype -am
      - name: 'Run proxy Kroxylicious integration tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # These variables/secrets support the Fortanix/KMS integration tests.   If the secrets are absent, the
          # tests will be skipped.
          KROXYLICIOUS_KMS_FORTANIX_API_ENDPOINT: ${{ vars.KROXYLICIOUS_KMS_FORTANIX_API_ENDPOINT }}
          KROXYLICIOUS_KMS_FORTANIX_ADMIN_API_KEY: ${{ secrets.KROXYLICIOUS_KMS_FORTANIX_ADMIN_API_KEY }}
          KROXYLICIOUS_KMS_FORTANIX_API_KEY: ${{ secrets.KROXYLICIOUS_KMS_FORTANIX_API_KEY }}
        working-directory: kroxylicious-integration-tests
        run: mvn -B verify -DskipUTs -Dit.test="${{ matrix.tests }}"
  integration_test_proxy:
    runs-on: ubuntu-latest
    needs: run_integration_tests
    if: always()
    permissions:
      actions: read
    steps:
    - name: 'Check all matrix builds'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        FAILED_JSON=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
          --jq '.jobs[] | select(.conclusion=="failure") | {name: .name, url: .html_url}')
        if [ -z "$FAILED_JSON" ]; then
          echo "All jobs passed!" >> $GITHUB_STEP_SUMMARY
          echo "No failures detected."
          exit 0
        fi
        echo "Failed Matrix Jobs" >> $GITHUB_STEP_SUMMARY
        echo "The following instances failed:"
        echo "$FAILED_JSON" | jq -r '"* [\(.name)](\(.url))"' >> $GITHUB_STEP_SUMMARY
        echo "$FAILED_JSON" | jq -r '"\(.name): \(.url)"'
        exit 1
  integration_test_filter_archetype:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: ./.github/actions/common/setup-java
      - name: 'Cache Maven packages'
        uses: ./.github/actions/common/cache-maven-packages
      - name: 'Build Kroxylicious archetype'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B install -DskipTests -Dmaven.javadoc.skip=true -DskipDocs=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Djapicmp.skip=true -pl :kroxylicious-bom,:kroxylicious-filter-archetype -am
      - name: 'run filter archetype integration tests'
        working-directory: kroxylicious-filter-archetype
        run: mvn -B verify