# kaf.yaml - builds and pushes a Kaf container image.
#
# Requires repository variables:
# - REGISTRY_SERVER - the server of the container registry service e.g. `quay.io` or `docker.io`
# - REGISTRY_USERNAME - - your username on the service (or username of your robot account)
# - REGISTRY_TOKEN - the access token that corresponds to `REGISTRY_USERNAME`
#

name: Kaf Container 
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository containing kaf'
        default: 'birdayz/kaf'
        required: true
      registry-destination:
        description: 'The release version, e.g. quay.io/<my org>/kaf'
        default: 'quay.io/kroxylicious/kaf'
        required: true
      ref:
        description: 'Ref (branch/tag) to build'
        required: true
        default: 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ vars.REGISTRY_SERVER != '' && vars.REGISTRY_USERNAME != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository:  ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - name: Login to container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ vars.REGISTRY_SERVER }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push Kaf container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
          push: true
          tags: ${{ github.event.inputs.registry-destination }}:${{ github.event.inputs.ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,compression=zstd